// throw new Error("this is err");

try {
    a;
} catch (error) {
    // console.log(error);
    console.log("ads");
}

//Can also handle exception using Promise in catch block